[package]
authors = ["Eduardo Lemos Rocha <dudulr10@gmail.com>"]
edition = "2021"
name = "rodo"
version = "0.1.0"

[dependencies]
clap = {version = "4.1.8", features = ["derive", "cargo"]}
nom = "7.1.3"
walkdir = "2.3.3"
